import localFont from "next/font/local";
import "../../globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1200px] mx-auto flex flex-col gap-20 min-h-screen`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
